name: Generate GitHub Pacman Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Pacman SVG
        uses: Platane/pacman@v1
        with:
          github_user_name: BrunaOGomes
          output_path: ./github-contribution-grid-pacman.svg

      - name: Push to output branch
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch
          git switch --create output || git switch output
          mv github-contribution-grid-pacman.svg ./github-contribution-grid-pacman.svg
          git add github-contribution-grid-pacman.svg
          git commit -m "update pacman svg" || echo "no changes"
          git push origin output
